// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateExam(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function CreateExamWithCSV(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:Array<string>,arg7:string):Promise<void>;

export function DeleteExam(arg1:number):Promise<void>;

export function DownloadStudentSheet(arg1:number):Promise<string>;

export function EvaluateExam(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ExportExamStudentsCSV(arg1:number):Promise<string>;

export function GenerateExamStatisticsPDF(arg1:number,arg2:Array<string>):Promise<string>;

export function GetExamAnswers(arg1:number):Promise<string>;

export function GetExamStats(arg1:number):Promise<main.ExamStats>;

export function GetSavePath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListConfigs():Promise<Array<string>>;

export function ListExams():Promise<Array<main.ExamSummary>>;

export function ListStudents():Promise<Array<main.StudentSummary>>;

export function OpenPath(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PickPDF():Promise<string>;

export function PrintExamPDF(arg1:number):Promise<string>;

export function PrintStudentSheet(arg1:number):Promise<string>;

export function SetSavePath(arg1:string):Promise<void>;
