// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateExam(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateExam'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateExamWithCSV(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateExamWithCSV'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteExam(arg1) {
  return window['go']['main']['App']['DeleteExam'](arg1);
}

export function DownloadStudentSheet(arg1) {
  return window['go']['main']['App']['DownloadStudentSheet'](arg1);
}

export function EvaluateExam(arg1, arg2, arg3) {
  return window['go']['main']['App']['EvaluateExam'](arg1, arg2, arg3);
}

export function ExportExamStudentsCSV(arg1) {
  return window['go']['main']['App']['ExportExamStudentsCSV'](arg1);
}

export function GenerateExamStatisticsPDF(arg1, arg2) {
  return window['go']['main']['App']['GenerateExamStatisticsPDF'](arg1, arg2);
}

export function GetExamAnswers(arg1) {
  return window['go']['main']['App']['GetExamAnswers'](arg1);
}

export function GetExamStats(arg1) {
  return window['go']['main']['App']['GetExamStats'](arg1);
}

export function GetSavePath() {
  return window['go']['main']['App']['GetSavePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ListExams() {
  return window['go']['main']['App']['ListExams']();
}

export function ListStudents() {
  return window['go']['main']['App']['ListStudents']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickPDF() {
  return window['go']['main']['App']['PickPDF']();
}

export function PrintExamPDF(arg1) {
  return window['go']['main']['App']['PrintExamPDF'](arg1);
}

export function PrintStudentSheet(arg1) {
  return window['go']['main']['App']['PrintStudentSheet'](arg1);
}

export function SetSavePath(arg1) {
  return window['go']['main']['App']['SetSavePath'](arg1);
}
